### PR TITLE
Page on using the PPA for Jammy

### PR DESCRIPTION
**Pull request by RJDan**
I have added the above page.

### CODE REVIEW

**Comment by Llandy3d** [comment]
thanks for the pr!
Github didn't seem to notify me about it 🤔 

I will try to do a fresh install on ubuntu 22.04 this week 👍

**Comment by Llandy3d** [comment]
The link doesn't seem to work. When trying to add the ppa it also seems to not find it, but I would say it would be better to advise to directly install from apt as an alternative.
I will be going through the entire process and update it for ubuntu 22.04, since ubuntu 21.04 the only difference should be `sudo apt install sway`
Thank you!

**Comment by RJDan** [comment]
Hey
I contacted Sunderland93 to ask what happened since I used the ppa. I installed sway without any problems.
I have had a far better experience than with the manual install in Jammy. For example, with the latest sway (and wlroots)  suspend, hibernate and clamshell work 'out the box' whereas with the manual install I gave up after some time trying to get it to work.

**Comment by RJDan** [comment]
This one works on my side:
https://launchpad.net/~samoilov-lex/+archive/ubuntu/sway
The instructions will be a bit different from what I sent through earlier, incase you want to give it a try.

The 'Ubuntu stable' ppa seems to be taken down but there is now a dev version.

**Comment by Llandy3d** [comment]
Thanks! I tried both this one and building from scratch (1.8-dev) and even if I managed to install/build I seem to have problems making it start to confirm it's working. It could be some incompatibility with the vm software but I don't have a physical machine to test it on... regardless I will start documenting them!

**Pull request closed without merging**
